### ISSUE TITLE
What is the frequency of refresh ? 

### ISSUE THREAD

**Issue by ollie2a** [icepick3000/AirtagAlex#12]
It's a great little script and still working now and easy to adapt, thanks for sharing with the community. 

Two questions I had if anyone know this answers : 

1) What is the frequency of refresh in the FindMy app on macOS ? I feel like I need to refresh it manually, and it does not really refresh in the background ... but I can't validate this

2) Is there a similar location on iPhone for the findMy history ? I read somewhere that the iPhone stores history as well but does not display it on the FindMy app. 

Many thanks

**Comment by icepick3000** [comment]
If the findmy app doesnt refresh you will need to install a 3rd party tool to simulate screenclicks (like clicking between the tags). There is one such tool called 'click' but you could also of course use applescript. 

There is no location history from the findmy app on the iphone to my knowledge. You can however run a modified version of this script on a jailbroken iphone.
