### ISSUE TITLE
Parsing Error - Items.data encrypted

### ISSUE THREAD

**Issue by Funi1234** [icepick3000/AirtagAlex#13]
Getting `jq: parse error: Invalid numeric literal at line 1, column 24` when i run the script.

I'm unsure if the FindMy data has always been encrypted but when i open the file I'm now seeing:
```
{'signature': b"...", 'encryptedData': b'...'}
```

Was this always the contents of that file or have apple done somthing?

**Comment by icepick3000** [comment]
Apple started doing this in their latest Max OSX Sonoma update.. nothing I can do about it.
