### ISSUE TITLE
Ventura issue

### ISSUE THREAD

**Issue by dennisbrouwer91** [icepick3000/AirtagAlex#2]
Hi,

Trying your script on the latest stable of Ventura, but the folder your script is trying to get the Items.data file from (~/Library/Caches/com.apple.findmy.fmipcore/Items.data) isn't available under Ventura 13.1.
Any idea?

**Comment by icepick3000** [comment]
It is.. I got it on Ventura and it's working fine. 
Up to what folder can you go in this path? ~/Library/Caches/com.apple.findmy.fmipcore/

**Comment by dennisbrouwer91** [comment]
I can get in to that folder, but then i get this : 
`dbrouwer@MBP com.apple.findmy.fmipcore % ls -latrh
total 0
ls: .: Operation not permitted`

**Comment by icepick3000** [comment]
Did you enable full disk access as described in the video?

**Comment by dennisbrouwer91** [comment]
I completely missed that, that fixed it. Thanks.
