### ISSUE TITLE
Subsystem Linux for Windows

### ISSUE THREAD

**Issue by TeSoad90** [icepick3000/AirtagAlex#9]
Hi trying to get this running in my WSL terminal using Ubuntu currently getting this error

jbmcnichol@DESKTOP-AGHPMOR:~/AirtagAlex$ ./AirtagAlex.sh
Creating a copy of Items.data to prevent potential file corruption
cp: cannot stat '/home/jbmcnichol/Library/Caches/com.apple.findmy.fmipcore/Items.data': No such file or directory
Failed to copy Items.data file. Please ensure Terminal has 'Full Disk Access' in the 'Privacy & Security' section in macOS Preferences

**Comment by icepick3000** [comment]
You need to grant the full disk access.. it's also shown in the video.
